services:
  open-fga-db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=fga
      - POSTGRES_USER=fga
      - POSTGRES_PASSWORD=fga
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U fga" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    depends_on:
      open-fga-db:
        condition: service_healthy
    image: openfga/openfga:latest
    container_name: migrate
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://fga:fga@open-fga-db:5432/fga?sslmode=disable
    command: migrate
    networks:
      - default

  open-fga:
    depends_on:
      migrate:
        condition: service_completed_successfully
    image: openfga/openfga:latest
    container_name: openfga
    command: run
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://fga:fga@open-fga-db:5432/fga?sslmode=disable
      - OPENFGA_DATASTORE_MAX_OPEN_CONNS=100
      - OPENFGA_PLAYGROUND_ENABLED=true
    networks:
      - default
    ports:
      - "8080:8080"
      - "8081:8081"
      - "3000:3000"
      - "2112:2112"
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/grpc_health_probe",
          "-addr=openfga:8081"
        ]
      interval: 5s
      timeout: 30s
      retries: 3